Test publish
NREL/Wattile pull request #273
Opened 2023-03-16 21:46 UTC by haneslinger

2023-03-16 22:12 UTC, anyaelena commented on pyproject.toml
> +description = "Deep learning algorithms for probabilistic forecasting of time series building performance data."
let's use "Probabilistic Deep Learning-based Forecasting of Building Energy Consumption"

2023-03-16 22:13 UTC, anyaelena requested changes
Please update description to "Probabilistic Deep Learning-based Forecasting of Building Energy Consumption" and we'll be good to go!  thank you!

2023-03-16 23:39 UTC, anyaelena commented on pyproject.toml
> +description = "Deep learning algorithms for probabilistic forecasting of time series building performance data."
yes please!

2023-03-17 01:24 UTC, stephen-frank approved these changes

2023-03-17 17:39 UTC, merged